#!/data/data/com.termux/files/usr/bin/bash

clear
kill_color=$'\e[0m'
command -v youtube-dl &>/dev/null || printf "\e[031m Please install Youtube-dl or run install.sh\n$kill_color"

#[[ -f ~/bin ]] || printf "\e[031mRun the install.sh script.\n$kill_color"
echo "

  
█▀▀ █░█ ▄▀█ █▄░█
██▄ ▀▄▀ █▀█ █░▀█

█░█ ▄▀█ ▀▄▀ ▀▄▀ ▀▄▀ █▀█ █▀█
█▀█ █▀█ █░█ █░█ █░█ █▄█ █▀▄
                  EVAN HAXXXOR 

              Download YouTube Video
              Download File YDownload"|lolcat                                                                      
echo " "
echo -e "\e[032m" "Coder---> Evan Al Mahmud Irfan." 
echo -e "\e[032m" "Github---> github.com/sacrobrent" 
echo -e "\e[032m" "FB---> m.me/E826.A5.M24683.I7326.O33icia55" 
echo -e "\e[032m" "FB---> m.me/Evan.Al.Mahmud.Irfan.Official.xDD" 
echo -e "\e[036m"
echo -e "\e[034m" "Select Song Quality" 
echo -e "\e[032m" "{1}~~~> Music MP3" 
echo -e "\e[032m" "{2}~~~> Video 360p" 
echo -e "\e[032m" "{3}~~~> Video 480p" 
echo -e "\e[032m" "{4}~~~> Video 720p" 
echo -e "\e[032m" "{5}~~~> Video 1080p" 
echo -e "\e[032m" "{6}~~~> Video 2160p" 
echo -e "\e[032m" "{e}~~~> EXIT" 
command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/YTDownloads/%(title)s.%(ext)s -f'

printf "\e[032m>>Choice Video Quality~~~> $kill_color"
read option

if [[ -z $option ]];
then
	clear
	printf "\e[031mPlease choose a option!\n$kill_color"
else
case $option in
	1)
	echo "$command 140" > ~/.config/youtube-dl/config #option 1
	youtube-dl $1
	;;
	2)
	echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config #option 2
	youtube-dl $1
	;;
	3)
	echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config #option 3
	youtube-dl $1
	;;
	4)
	echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config #option 4
	youtube-dl $1
	;;
	5)
	echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config #option 5
	youtube-dl $1
	;;
	6)
	echo "$command \"best[height<=2160]\"" > ~/.config/youtube-dl/config
    	youtube-dl $1
	;;
	e)
	break
	;;
esac 
fi
